export const mockGeoData = [
    { name: "United States", value: Math.floor(Math.random() * 1000) },
    { name: "China", value: Math.floor(Math.random() * 1000) },
    { name: "India", value: Math.floor(Math.random() * 1000) },
    { name: "Brazil", value: Math.floor(Math.random() * 1000) },
    { name: "Russia", value: Math.floor(Math.random() * 1000) },
    { name: "Germany", value: Math.floor(Math.random() * 1000) },
    { name: "United Kingdom", value: Math.floor(Math.random() * 1000) },
    { name: "France", value: Math.floor(Math.random() * 1000) },
    { name: "Japan", value: Math.floor(Math.random() * 1000) },
    { name: "Canada", value: Math.floor(Math.random() * 1000) },
    { name: "Australia", value: Math.floor(Math.random() * 1000) },
    { name: "Mexico", value: Math.floor(Math.random() * 1000) },
    { name: "South Africa", value: Math.floor(Math.random() * 1000) },
    { name: "Argentina", value: Math.floor(Math.random() * 1000) },
    { name: "Saudi Arabia", value: Math.floor(Math.random() * 1000) },
    { name: "Turkey", value: Math.floor(Math.random() * 1000) },
    { name: "Italy", value: Math.floor(Math.random() * 1000) },
    { name: "South Korea", value: Math.floor(Math.random() * 1000) },
    { name: "Indonesia", value: Math.floor(Math.random() * 1000) },
    { name: "Spain", value: Math.floor(Math.random() * 1000) },
    { name: "Pakistan", value: Math.floor(Math.random() * 1000) },
    { name: "Bangladesh", value: Math.floor(Math.random() * 1000) },
    { name: "Nigeria", value: Math.floor(Math.random() * 1000) },
    { name: "Egypt", value: Math.floor(Math.random() * 1000) },
    { name: "Vietnam", value: Math.floor(Math.random() * 1000) },
    { name: "Iran", value: Math.floor(Math.random() * 1000) },
    { name: "Philippines", value: Math.floor(Math.random() * 1000) },
    { name: "Thailand", value: Math.floor(Math.random() * 1000) },
    { name: "Colombia", value: Math.floor(Math.random() * 1000) },
    { name: "Ukraine", value: Math.floor(Math.random() * 1000) },
    { name: "Poland", value: Math.floor(Math.random() * 1000) },
    { name: "Netherlands", value: Math.floor(Math.random() * 1000) },
    { name: "Ethiopia", value: Math.floor(Math.random() * 1000) },
    { name: "Iraq", value: Math.floor(Math.random() * 1000) },
    { name: "South Sudan", value: Math.floor(Math.random() * 1000) },
    { name: "Kenya", value: Math.floor(Math.random() * 1000) },
    { name: "Myanmar", value: Math.floor(Math.random() * 1000) },
    { name: "Venezuela", value: Math.floor(Math.random() * 1000) },
    { name: "Morocco", value: Math.floor(Math.random() * 1000) },
  ];
  